"""
LangGraph State Definition for EasySQL Agent.
"""

from typing import Annotated, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class ContextOutputDict(TypedDict):
    """Structured output from ContextBuilder."""

    system_prompt: str
    user_prompt: str
    total_tokens: int


class ValidationResultDict(TypedDict):
    """Structured validation result."""

    valid: bool
    details: str | None
    error: str | None


class SchemaHintColumn(TypedDict):
    """Schema hint for a single column."""

    table_name: str
    column_name: str
    chinese_name: str | None
    data_type: str
    is_pk: bool
    is_fk: bool
    is_time: bool


class SchemaHintTable(TypedDict):
    """Schema hint for a single table."""

    name: str
    chinese_name: str | None
    description: str | None
    score: float
    key_columns: list[SchemaHintColumn]


class SchemaHintDict(TypedDict):
    """Schema hint with tables and semantic columns for analyze context."""

    tables: list[SchemaHintTable]
    semantic_columns: list[SchemaHintColumn]


class ConversationTurn(TypedDict):
    """Single conversation turn for history tracking."""

    message_id: str
    question: str
    sql: str | None
    tables_used: list[str]
    token_count: int


class EasySQLState(TypedDict):
    """
    Global state for the EasySQL LangGraph Agent.

    Attributes:
        raw_query: The original user question.
        clarified_query: The refined query after HITL (if needed).
        clarification_questions: Questions to ask user for clarification.

        messages: Chat history (Annotated with add_messages for accumulation).

        schema_hint: Lightweight schema context for analyze node (plan mode only).
            Contains top-k table names, descriptions for schema-aware clarification.
        retrieval_result: Output from SchemaRetrievalService (serialized dict).
            Note: This is a serialized RetrievalResult.__dict__ for state compatibility.
        context_output: Structured output from ContextBuilder.

        generated_sql: The SQL generated by the LLM.
        validation_result: Structured result of the SQL validation.
        validation_passed: Whether the SQL passed validation.

        retry_count: Number of times SQL generation has been retried.
        error: Latest error message if any.

        db_name: Target database name for query execution.
    """

    # --- Input & Conversation ---
    raw_query: str
    clarified_query: str | None
    clarification_questions: list[str] | None
    messages: Annotated[list[BaseMessage], add_messages]

    # --- Context Layer Data ---
    # Schema hint: lightweight schema for analyze node (plan mode)
    schema_hint: SchemaHintDict | None
    # Full retrieval result (serialized RetrievalResult for JSON compatibility)
    retrieval_result: dict | None
    context_output: ContextOutputDict | None
    # Code context: formatted code snippets for context (from retrieve_code node)
    code_context: str | None

    # --- Execution Layer Data ---
    generated_sql: str | None
    validation_result: ValidationResultDict | None
    validation_passed: bool

    # --- Control Flow ---
    retry_count: int
    error: str | None

    # --- Options ---
    db_name: str | None

    # --- Multi-turn Conversation ---
    conversation_history: list[ConversationTurn] | None
    cached_context: ContextOutputDict | None
    current_message_id: str | None
    parent_message_id: str | None
    needs_new_retrieval: bool
    shift_reason: str | None
    history_summary: str | None
