"""
LangGraph State Definition for EasySQL Agent.
"""

from typing import Annotated, List, Optional, TypedDict
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class ContextOutputDict(TypedDict):
    """Structured output from ContextBuilder."""
    system_prompt: str
    user_prompt: str
    total_tokens: int


class ValidationResultDict(TypedDict):
    """Structured validation result."""
    valid: bool
    details: Optional[str]
    error: Optional[str]


class EasySQLState(TypedDict):
    """
    Global state for the EasySQL LangGraph Agent.
    
    Attributes:
        raw_query: The original user question.
        clarified_query: The refined query after HITL (if needed).
        clarification_questions: Questions to ask user for clarification.
        
        messages: Chat history (Annotated with add_messages for accumulation).
        
        retrieval_result: Output from SchemaRetrievalService (serialized dict).
            Note: This is a serialized RetrievalResult.__dict__ for state compatibility.
        context_output: Structured output from ContextBuilder.
        
        generated_sql: The SQL generated by the LLM.
        validation_result: Structured result of the SQL validation.
        validation_passed: Whether the SQL passed validation.
        
        retry_count: Number of times SQL generation has been retried.
        error: Latest error message if any.
        
        db_name: Target database name for query execution.
    """
    
    # --- Input & Conversation ---
    raw_query: str
    clarified_query: Optional[str]
    clarification_questions: Optional[List[str]]
    messages: Annotated[List[BaseMessage], add_messages]
    
    # --- Context Layer Data ---
    # Note: retrieval_result is serialized RetrievalResult for JSON compatibility
    retrieval_result: Optional[dict]
    context_output: Optional[ContextOutputDict]
    
    # --- Execution Layer Data ---
    generated_sql: Optional[str]
    validation_result: Optional[ValidationResultDict]
    validation_passed: bool
    
    # --- Control Flow ---
    retry_count: int
    error: Optional[str]
    
    # --- Options ---
    db_name: Optional[str]

